import { Activity, Expense, Memory } from './types';

export const ACTIVITIES: Activity[] = [
  {
    id: '1',
    day: 1,
    time: '08:00',
    period: 'Sáng',
    title: 'Khởi hành từ Sài Gòn',
    location: 'Bến xe Miền Đông',
    description: 'Di chuyển bằng xe Limousine Hoa Mai, dự kiến đến Vũng Tàu sau 2 tiếng.',
  },
  {
    id: '2',
    day: 1,
    time: '11:30',
    period: 'Trưa',
    title: 'Ăn trưa Bánh Khọt Cô Ba',
    location: '01 Hoàng Hoa Thám',
    description: 'Thưởng thức đặc sản bánh khọt tôm nhảy nổi tiếng nhất Vũng Tàu.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBIpZzep3bN3Z-CyyKJvpHmNZ4TLBgkcbN9jyolnxxyDb-LVnDjwAjuJ3iFOeq-Ovnw1l7wEx58wk_Jir6iSq9lGx1jjwBsbfuKQbiP1bAgye-wcUlE3wkoVi5hbq-R_q7F35Uagw0qKWzqtBEg0prmv-soiAaBpMFCNnMi9-rKIiS3foezEgLEEZ1w6F5R1Tmyef1fOwMHVCmomCGHeb-wJGVJ54eZaVXwXQA5eLbb0NhV3-YRBKC9uzSYJPxHZ6LcPADuTx_8cjw',
  },
  {
    id: '3',
    day: 2,
    time: '05:30',
    period: 'Sáng',
    title: 'Ngắm bình minh Bãi Trước',
    location: 'Công viên Bãi Trước',
    description: 'Đi dạo dọc bờ biển và đón những tia nắng đầu tiên của ngày mới.',
  },
  {
    id: '4',
    day: 2,
    time: '15:00',
    period: 'Chiều',
    title: 'Cà phê Soho Coffee',
    location: '66 Hạ Long',
    description: 'Check-in quán cà phê tông trắng cực hot view biển toàn cảnh.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCkKKx0MIEZTMDjksHMqZ2Iq_r3yZ3tRpzydEc58_HiSyrbmntiq-5qbTJB8rFVKHJb36mptiYAigKLJQF5g428mDxTeH3jGqAG3QktbpEwI7xKT4v7d-lDJ4pj3XCbwQcEp_G8XHYvd0djVUxnuqOyzV9L4QWoMUNilEbg1E69gFA8keM0cg2AMQ3DKUU_16D9TcH22iQigwvxUlIxjcWW-Kal2vP77dhhkTyDxQlvbMwE1R0VfB6YyUElH7o7TfZqXXiKpg1A0Ms',
  },
];

export const EXPENSES: Expense[] = [
  {
    id: '1',
    payer: 'Nguyễn Văn An',
    payerInitials: 'AN',
    reason: 'Thuê biệt thự nghỉ dưỡng (2 đêm)',
    date: '14/10/2023',
    amount: 8500000,
    colorClass: 'bg-primary-fixed text-primary',
  },
  {
    id: '2',
    payer: 'Trần Thị Hoa Lan',
    payerInitials: 'HL',
    reason: 'Tiệc hải sản tối đầu tiên',
    date: '14/10/2023',
    amount: 4200000,
    colorClass: 'bg-secondary-fixed text-on-secondary-fixed',
  },
  {
    id: '3',
    payer: 'Lê Minh Tú',
    payerInitials: 'MT',
    reason: 'Xăng xe & Phí cầu đường',
    date: '15/10/2023',
    amount: 1500000,
    colorClass: 'bg-tertiary-fixed text-on-tertiary-fixed',
  },
  {
    id: '4',
    payer: 'Nguyễn Văn An',
    payerInitials: 'AN',
    reason: 'Vé tham quan Ngọn Hải Đăng',
    date: '15/10/2023',
    amount: 1200000,
    colorClass: 'bg-primary-fixed text-primary',
  },
];

export const MEMORIES: Memory[] = [
  {
    id: '1',
    title: 'Bình minh rạng rỡ',
    caption: '"Khoảnh khắc đầu tiên khi chạm chân đến cát."',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD8vJZTCrOxPbPg1KwA5D4JuVCqsqXQd2MrC9enVztc0EfsmEmbMUAk-1JLS77CBbak2nzUQxAqPkzR316cq3GTZtWO0VxTXvfTFovtYoS_LsZq1H3Fv2mOyPTxxJZBMEy9E1XDF37Xo3kkNE3kaGXeCe6QvzGb7BJq960XWGwDyJ9n9ZRHKaQS5v8QCzo_zMdmTcbAQvWl5sjaHWOlUQLI1PAxJgf7uisEZO34fH12HNKqfb2zZw1qMsiq1pGDm8-0sqe53L8KcUw',
    category: 'Bãi Sau',
  },
  {
    id: '2',
    title: 'Đỉnh Hải Đăng',
    caption: 'Một buổi chiều lộng gió nhìn xuống toàn thành phố.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBA0O9om87OcHB-uyKB2YV4n06d_5woszreUvmK9gs2e9vD7a1XVbAX6xcRPIPNGJYzw38iG1ZbJuxO8CFk1fhtujBElsoD5SM8a95iwoAWgE41b0jUSp1qKXoDRLjYDhVesbnr72VYWeMW_F6UuH-o9zYpgAcRQbItdbGnB6xoApSX2D1gompFG5KPTYB_fxJEb7MQxLSB0ah2-GlnNTcK5lmeWsNUbbnuejVwOJ4bwO9eTC1hhNav5zSFjp0-Ka7A8K9TZ8KFDI',
    category: 'Hải Đăng',
    aspectRatio: 'aspect-[4/5]',
  },
  {
    id: '3',
    title: 'Tiệc hải sản đêm',
    caption: 'Không thể thiếu món ốc vú nàng tại quán địa phương.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCoOzDsLyjoMEKiISKjI2PZ0WpQfFAW8d8AuzOVqQjgNaiObdYMc8qNY3FNDsg7jCOWK-pSrwTZzEykyKHTA9bA_ljVrf4usjGJZmJE1jI_SStp5uWekz6rILxOAfHDi3njSnWE0-IEc7fhmTNBtKshKd0iFPE7pmRWiPsz0ZztFXPQmpenGMjB3xaOtSwe4c-8_dbMYTlg15kGR7DFhC_IZV313Giy6TLEiV59QDydqf32qVW3G2Wvh-UL_-dgxXG_A4DABFqziOY',
    category: 'Ẩm thực',
    aspectRatio: 'aspect-square',
  },
  {
    id: '4',
    title: 'Cùng nhau đi trốn',
    caption: 'Team mình đi đâu cũng vui, miễn là cùng nhau.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDAgFI5JosUWCfSpQb7rLWvQUsMyIzZ2200o_1gJoG8vpPBY54BmqG3V6xvdgGcnKxVoQWVFNFhyqVX3E8DOScuAX0rtuyKu_YZWE4dscXqDPKl811m0g2L5xUfFd8MAYoxg1vqwHiqw0QGxVXAke-COaDPUaJWi6BOyHGsRTGKd6nrGc7lfahp0d3FU60I7ofmfMYC3Pp8Raso8pcT5AOpUjJ1xDNSGm_GQAkvTO6RimQy8CmCLkZSIkGRDleF-Dwybhu1425scOY',
    category: 'Đồng đội',
  },
  {
    id: '5',
    title: 'Tượng Chúa Kitô Vua',
    caption: '"Gần 1000 bậc thang đáng giá từng bước chân."',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD5qe85wQZ58aGMtFW0PrhCK9HlukwEA_0nYyrNFWYpKou_M3-9xhBp261IFy-yNKW3gvzS6-1iA-RnR0OdJxuIaEm2xn1BrfiC-RfQEAlgcdOn5RuTv-J-LUM8ao1ob6bnF7IHz0EHA7pQipn0DnrshYLn46Gt_x5cQCoImkd8TI2KEqmGUJaPaYZSRrvkNh-lIMFGOIe9unhBO6tg7pwzms0YD2oPA2iEMNXcxsgBVIisZsj0QJxyZynsZ4UDsL8EUzcPrTSBec4',
    category: 'Bãi Sau',
    aspectRatio: 'aspect-[2/3]',
  },
  {
    id: '6',
    title: 'Góc nhỏ bình yên',
    caption: 'Trốn nắng tại một tiệm cafe xinh xắn ven đường Thùy Vân.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUMDPp1ulmvX_lyrTL2mACMyjdaPOaPmXfLIuLFBx5RMGDg7PC9Qg5aSmCn0z3hyR4JyxF65TlEqeiRdWJmZJlGk-PgZ7ejTOd-05z_oDZe7gRA1VfsbjN1V0p5Lg52JX4AvCpWRc27Ajwfp05vSx8wjBVKdpEyMQqlfcLqfOnkUf8rgXbWg8P6WMX2OD-DJBU8X4jYvDaemVT3KRF0U1MOK26Cs3rA1R2GSb7nKqVy_4AbqMdAhZ3DexCly5986aK4wkWiD2HfO8',
    category: 'Ẩm thực',
  },
];
